name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type-check & build
        run: yarn build

      - name: Install Playwright browsers (caches automatically)
        uses: microsoft/playwright-github-action@v1

      - name: Run Playwright tests
        run: yarn test